# Generated by Django 3.2.2 on 2021-08-26 12:23

from django.db import migrations, models
import ecommerce.models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0004_items_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='image',
            field=models.ImageField(upload_to=ecommerce.models.path_and_rename),
        ),
    ]
