# Generated by Django 3.2.2 on 2021-08-26 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_category_trending'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='count',
        ),
        migrations.RemoveField(
            model_name='subcategory',
            name='count',
        ),
    ]
