# Generated by Django 3.2.2 on 2021-08-26 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_items_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
