# Generated by Django 3.2.2 on 2021-08-26 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_remove_subcategory_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='deal_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='items',
            name='deal_of_day',
            field=models.BooleanField(default=False),
        ),
    ]
